# Generated by Django 3.0.10 on 2020-09-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200908_1601'),
        ('api', '0004_lesson_teacher'),
    ]

    operations = [
    ]
