# Generated by Django 3.0.10 on 2020-09-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20200910_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
